# Generated by Django 4.2.3 on 2023-07-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfcertificate', '0002_remove_certificate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='custom_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
